version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/otknoy/dmm-crawler
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep && dep ensure
      - run: go test -v -race ./...
      - run: go build ./

  test:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/otknoy/dmm-crawler
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep && dep ensure
      - run: go test -v -race ./...
